PROJECT_NAME=StrictlyPositiveCert

# OPTIONS:
#FLAGS+=-DENABLE_VERIFICATION
#FLAGS+=-DENABLE_BINARY_SEARCH_AVKL
#FLAGS+=-DENABLE_BINARY_SEARCH_LS
#FLAGS+=-DENABLE_N_HEURISTIC
#FLAGS+=-DENABLE_AVERKOV_CHECK
#FLAGS+=-DENABLE_POST_OPT
#FLAGS+=-DENABLE_QUICK_CERT
#FLAGS+=-DWEIFENG_OPTIMIZATION
#FLAGS+=-DLOG_TIME

#DEBUG_MODE+=-DENABLE_DEBUGGING

#VALUES+=-DEPS_FACTOR=<rational>
#VALUES+=-DN_GUESS_AVKL=<integer>
#VALUES+=-DN_GUESS_LS=<integer>

FLAGS=
DEBUG_MODE=
VALUES=

FLAGS+=-DENABLE_BINARY_SEARCH_AVKL
VALUES+=-DEPS_FACTOR=1/100
VALUES+=-DN_GUESS_AVKL=70
VALUES+=-DN_GUESS_LS=600

.PHONY: clean

all: ${PROJECT_NAME}.mla

${PROJECT_NAME}.mla: src/${PROJECT_NAME}.mpl
	maple ${FLAGS} ${DEBUG_MODE} ${VALUES} ./scripts/installation_script.mpl

clean:
	rm -rf ${PROJECT_NAME}.mla
